name: 'Daffy Gift Action'
description: 'Gift a charitable donation to a GitHub user who fixes an Issue.'
author: 'Donavon West - Daffy.org'
inputs:
  github_token:
    required: true
    description: 'Your GitHub token.'
  daffy_api_key:
    required: true
    description: 'Your Daffy API key. Learn more at https://docs.daffy.org'
runs:
  using: 'node16'
  main: 'dist/index.js'
