name: Dump GitHub context

on:
  pull_request:
    types: [closed]
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github) }}
